pipelines: Update to rust 1.75.0
Fixes the error below:

error: package `clap_builder v4.4.7` cannot be built because it requires rustc 1.70.0 or newer

Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>